ticket/home/urls.py
from django.urls import path
from . import views

app_name='home'

urlpatterns = [
    path('',views.HomeView.as_view(),name='home'),
    path('register/',views.UserRegisterView.as_view(),name='register'),
    path('login/',views.UserLoginView.as_view(),name='login'),
    path('logout/',views.UserLogoutView.as_view(),name='logout'),
    path('profile/<int:user_id>/',views.ProfileView.as_view(),name='profile'),
    path('messages/',views.MessagesView.as_view(),name='messages'),
    path('chat/<int:ticket_id>/',views.ChatView.as_view(),name='chat'),
    path('answer/<int:ticket_id>/',views.AnswerView.as_view(),name='answer'),
]

ticket/ticket/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
]

ticket/templates/inc/messages.html
{% if messages %}
    {% for msg in messages %}
        <p class="alert alert-{{ msg.tags }}">{{ msg }}</p>
    {% endfor %}
{% endif %}

ticket/templates/inc/navbar.html
<nav class="navbar navbar-expand-lg bg-dark">
  <div class="container-fluid">
      <div class="navbar-nav">
            {% if request.user.is_authenticated %}
                <a class="nav-link active"  href="{% url 'home:home' %}">home</a>
                <a class="nav-link active"  href="{% url 'home:logout' %}">logout</a>
                <a class="nav-link active"  href="{% url 'home:profile'  user.id %}">profile</a>
            {% else %}
                <a class="nav-link active"  href="{% url 'home:home' %}">home</a>
                <a class="nav-link active"  href="{% url 'home:register' %}">Register</a>
            {% endif %}
      </div>
  </div>
</nav>