ticket/home/urls.py
from django.urls import path
from . import views

app_name='home'

urlpatterns = [
    path('',views.HomeView.as_view(),name='home'),
    path('register/',views.UserRegisterView.as_view(),name='register'),
    path('login/',views.UserLoginView.as_view(),name='login'),
    path('logout/',views.UserLogoutView.as_view(),name='logout'),
    path('profile/<int:user_id>/',views.ProfileView.as_view(),name='profile'),
    path('messages/',views.MessagesView.as_view(),name='messages'),
    path('chat/<int:ticket_id>/',views.ChatView.as_view(),name='chat'),
    path('answer/<int:ticket_id>/',views.AnswerView.as_view(),name='answer'),
]

ticket/ticket/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
]

ticket/home/models.py
from django.db import models
from django.contrib.auth.models import User

"""
    Creating two ticket and response models 
    and using the Django user model for authentication
"""

class Ticket(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE, related_name='uticket')
    superuser=models.ForeignKey(User,on_delete=models.CASCADE,related_name='sticket')
    title=models.CharField(max_length=50)
    body=models.TextField(max_length=400)
    created=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user}-{self.body[:30]}'


class Answer(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='Uanswer')
    ticket = models.ForeignKey(Ticket, on_delete=models.CASCADE, related_name='Tanswer')
    answer = models.ForeignKey('self', on_delete=models.CASCADE, related_name='Answer', blank=True, null=True)
    is_answer = models.BooleanField(default=False)
    body = models.TextField(max_length=400)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user}-{self.body[:30]}'

ticket/home/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .froms import UserLoginForm, UserRegisterForm, TiketForm, AnswerMessageForm
from django.views import View
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from .models import Ticket


# only for login user and Display the login form
class HomeView(View):
    form_class = UserLoginForm

    def get(self, request):
        form = self.form_class
        return render(request, 'home/home.html', {'form': form})


class UserRegisterView(View):
    form_class = UserRegisterForm
    templates_class = 'home/register.html'

    # Disable registration for users who have already registered
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            messages.error(request, 'your are logged in and you cant do this')
            return redirect('home:home')
        return super().dispatch(request, *args, **kwargs)

    # Display UserRegisterForm for registration
    def get(self, request):
        form = self.form_class
        return render(request, self.templates_class, {'form': form})

    # Save the input information in the user model to create a new user account
    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            User.objects.create_user(cd['username'], cd['email'], cd['password1'])
            messages.success(request, 'your account is successfuly created', 'success')
            return redirect('home:home')
        return render(request, self.templates_class, {'form': form})


class UserLoginView(View):
    form_class = UserLoginForm
    templates_name = 'home/home.html'

    # To avoid frequent connection to the database and connect to the database only when needed
    def setup(self, request, *args, **kwargs):
        self.next = request.GET.get('next')
        return super().setup(request, *args, **kwargs)

    # Disable login for users who have already logined
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            messages.error(request, 'your are logged in befor')
            return redirect('home:home')
        return super().dispatch(request, *args, **kwargs)

    # Display UserLoginForm for Login
    def get(self, request):
        form = self.form_class
        return render(request, self.templates_name, {'form': form})

    # Checking user input information and user login if correct
    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(username=cd['username'], password=cd['password'])
            if user is not None:
                login(request, user)
                messages.success(request, 'your successfuly loged in', 'success')
                if self.next:
                    return redirect(self.next)
                return redirect('home:profile', request.user.id)
            messages.error(request, 'your password or username isnot correct', 'danger')
        return render(request, self.templates_name, {'form': form})


class UserLogoutView(LoginRequiredMixin, View):
    def get(self, request):
        logout(request)
        messages.success(request, 'your logout is successfuly done', 'success')
        return redirect('home:home')


class ProfileView(LoginRequiredMixin, View):
    """
        Checking the type of user (admin and normal user)
         and if it is an admin,
         all users' messages will be displayed,
          and if it is a normal user,
           it will display the user's own messages.
    """

    def get(self, request, user_id):
        user = get_object_or_404(User, pk=user_id)
        if request.user.is_superuser:
            uticket = Ticket.objects.all()
            messages.success(request, 'hello you are admin, welcome to your profile', 'success')
        else:
            uticket = user.uticket.filter(user=user)
            messages.success(request, 'hello you are user,welcome to you are profile', 'success')
        return render(request, 'home/profile.html', {'uticket': uticket})


class MessagesView(LoginRequiredMixin, View):
    form_class = TiketForm

    # Display TiketForm for create message
    def get(self, request):
        form = self.form_class
        return render(request, 'home/message.html', {'form': form})

    # Save the input information in the Ticket model to create a new message
    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            new_message = form.save(commit=False)
            new_message.user = request.user
            new_message.superuser = request.user
            new_message.title = cd['title']
            new_message.body = cd['body']
            new_message.save()
            messages.success(request, 'your messages is successfuly sended wait for your answer', 'success')
            return redirect('home:profile', request.user.id)
        return render(request, 'home/message.html', {'form': form})


class ChatView(LoginRequiredMixin, View):

    # For user that be admin to close the chat and end that message
    def setup(self, request, *args, **kwargs):
        self.ticket_instance = get_object_or_404(Ticket, pk=kwargs['ticket_id'])
        return super().setup(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        Ticket_answer = self.ticket_instance.Tanswer.filter(is_answer=False)
        close = False
        if request.user.is_superuser:
            close = True
        return render(request, 'home/chat.html',
                      {'ticket': self.ticket_instance, 'Ticket_answer': Ticket_answer, 'close': close})


class AnswerView(LoginRequiredMixin, View):
    form_class = AnswerMessageForm

    # Calling the desired message using ticket ID
    def setup(self, request, *args, **kwargs):
        self.ticket_instance = get_object_or_404(Ticket, pk=kwargs['ticket_id'])
        return super().setup(request, *args, **kwargs)

    # Display AnswerMessageForm for answer to  desired message
    def get(self, request, *args, **kwargs):
        return render(request, 'home/answer.html', {'form': self.form_class})

    # Save the input answer in the Ticket model to create a new message after check the user is logged in
    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.user = request.user
            answer.ticket = self.ticket_instance
            answer.save()
            messages.success(request, 'your answer is successfully submit', 'success')
            return redirect('home:chat', self.ticket_instance.id)

ticket/home/templates/home/answer.html
{% extends 'base.html' %}

{% block content %}

     {% if request.user.is_authenticated%}
            <form action="" method="post">
                 {% csrf_token %}
                 {{ form.as_p }}
                 <input type="submit" value="send">
            </form><br/>
    {% else %}
        <p class="alert alert-danger"> only login user can send messages</p>
    {% endif %}
{% endblock %}

ticket/home/templates/home/chat.html
{% extends 'base.html' %}

{% block content %}
             {% if user.is_superuser %}
                    <a href="{%url 'home:chat' ticket.id %}" class=" btn btn-primary col-md-2">close chat</a>
                     <a href="{%url 'home:answer' ticket.id%}" class=" btn btn-primary" >Answer</a><br/>

            {% else %}
                 <a href="{%url 'home:answer' ticket.id%}" class="{% if close %} disabled{% endif %} btn btn-primary" >Answer</a><br/>

            {% endif %}
        <p>{{ ticket.user }}</p>
        <p>{{ ticket.title}}-{{ ticket.created }}</p>
        <p>{{ ticket.body }}</p><br/>

        <p>{{ Ticket_answer.count }} answer</p>
        {% for answer in Ticket_answer  %}
                <div class="card text-bg-info mb-3" style="max-width: 18rem;">
                <div class="card-header">{{ answer.user }}| {{ answer.created|timesince }}</div>
                <div class="card-body">
                     <p class="card-text">{{ answer.body }}</p>
                </div>
                </div>
        {% endfor %}

{% endblock %}

ticket/home/templates/home/home.html
{% extends 'base.html' %}

{% block content %}
    <form action="{% url 'home:login'%}" method="post" class="col-2">
        {% csrf_token %}
        {{ form.as_p }}
    <input type="submit" value="login">
    </form>
{% endblock %}

ticket/home/templates/home/message.html
{% extends 'base.html' %}
{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p}}
    <input type="submit" value="send">
    </form>
{% endblock %}

ticket/home/templates/home/profile.html
{% extends 'base.html' %}
{% block content %}
    <a href="{%url 'home:messages'%}" class="btn btn-primary" >new message</a><br/>

    <div class="card">
        {% for ticket in uticket %}
            <a href="{% url 'home:chat' ticket.id %}" class="card-body" > {{ ticket.user }} - {{ ticket.title}}</a><br/>
        {% endfor %}
    </div>
{% endblock %}

ticket/home/templates/home/register.html
{% extends 'base.html' %}

{% block content %}
    <form action="" method="post" class="col-3">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="register">
</form>
{% endblock %}